"use server";
import { prisma } from "@/server/db";
import { authFilterQuery } from "@/server/lib/utils/query-clients";

export const getUserCertificate = authFilterQuery(async (search, session) => {
  return await prisma.user.findFirst({
    where: {
      organizationId: session.organizationId,
      id: search,
    },
    select: {
      id: true,
      lifeguardLicense: true,
      lifeguardLicenseExpiration: true,
      snorkelLicense: true,
      snorkelLicenseExpiration: true,
      lifeguardWaterRescueService: true,
      lifeguardWaterRescueServiceExpiration: true,
      waterRescuer: true,
      waterRescuerExpiration: true,
      riverRescuer: true,
      riverRescuerExpiration: true,
      medicalTraining: true,
      medicalTrainingExpiration: true,
      paramedicHelper: true,
      paramedicHelperExpiration: true,
      paramedic: true,
      paramedicExpiration: true,
      paramedicAssistance: true,
      paramedicAssistanceExpiration: true,
      paramedicEmergency: true,
      paramedicEmergencyExpiration: true,
      physician: true,
      physicianExpiration: true,
      physicianEmergency: true,
      physicianEmergencyExpiration: true,
      squadLeader: true,
      squadLeaderExpiration: true,
      groupLeader: true,
      groupLeaderExpiration: true,
      guardLeader: true,
      guardLeaderExpiration: true,
      trainLeader: true,
      trainLeaderExpiration: true,
      carDrivingLicense: true,
      carDrivingLicenseExpiration: true,
      blueLightInstruction: true,
      blueLightInstructionExpiration: true,
      boatmanLake: true,
      boatmanLakeExpiration: true,
      boatmanInland: true,
      boatmanInlandExpiration: true,
      lifeboatOperator: true,
      lifeboatOperatorExpiration: true,
      rwcPilotStage: true,
      rwcPilotStageExpiration: true,
      srcCertificate: true,
      srcCertificateExpiration: true,
      bosCertificate: true,
      bosCertificateExpiration: true,
      droneClass: true,
      droneClassExpiration: true,
      volunteerDataSheet: true,
      volunteerDataSheetExpiration: true,
      youthLeaderCard: true,
      youthLeaderCardExpiration: true,
      instructorSwimmer: true,
      instructorSwimmerExpiration: true,
      lifeguardInstructor: true,
      lifeguardInstructorExpiration: true,
      instructorWaterRescuer: true,
      instructorWaterRescuerExpiration: true,
      instructorMedicalService: true,
      instructorMedicalServiceExpiration: true,
      guardWalker: true,
      guardWalkerExpiration: true,
      boat: true,
      boatExpiration: true,
      car: true,
      carExpiration: true,
      rwc: true,
      rwcExpiration: true,
      guardLeaderInstruction: true,
      guardLeaderInstructionExpiration: true,
    },
  });
}, "readUser");

export type UserCertificateProps = NonNullable<
  Awaited<ReturnType<typeof getUserCertificate>>
>;
